import Head from "next/head";
const Home = () => {
  return (
    <>
      <Head>
        <title>Admin | DashBoard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="wrapper">
      </div>
    </>
  );
};

export default Home;
